name: "Lint"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.1.1"

        - name: "Set up Python"
          uses: actions/setup-python@v4.7.1
          with:
            python-version: "3.11"
            cache: "pip"

        - name: "Install requirements"
          run: python3 -m pip install poetry~=1.7 && poetry install

        - name: "Run"
          run: poetry run ./scripts/lint
